/**
 * @description       : 
 * @author            : Sangamesh Gella - ABSYZ Software Consulting Private Limited
 * @group             : 
 * @last modified on  : 04-08-2023
 * @last modified by  : Sangamesh Gella - ABSYZ Software Consulting Private Limited
 * Modifications Log
 * Ver   Date         Author                                                        Modification
 * 1.0   04-08-2023   Sangamesh Gella - ABSYZ Software Consulting Private Limited   Initial Version
**/
public class JSON2ApexChatGPTRegex{
	
	public cls_choices[] choices;

	public class cls_choices {
		public String text;
		public Integer index;
		public String finish_reason;
	}
}