/**
 * @description       : 
 * @author            : Sangamesh Gella - ABSYZ Software Consulting Private Limited
 * @group             : 
 * @last modified on  : 03-28-2023
 * @last modified by  : Sangamesh Gella - ABSYZ Software Consulting Private Limited
 * Modifications Log
 * Ver   Date         Author                                                        Modification
 * 1.0   03-28-2023   Sangamesh Gella - ABSYZ Software Consulting Private Limited   Initial Version
**/
public class JSON2ApexChatGPTImage{
	public Integer created;	
	public cls_data[] data;
	class cls_data {
		public String url;
	}
}